config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 resources :team, only: [:index]
 resources :contact, only: [:index]
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord

	has_many :users

	validates :name, 
	    presence: true,
		length: { in: 2..40 }
	validates :zip_code, 
	    presence: true,
  		length: { is: 5 }
  		
end

app/models/comment.rb
class Comment < ApplicationRecord
      belongs_to :gossip
      belongs_to :user

end

app/models/gossip.rb
class Gossip < ApplicationRecord

    belongs_to :user
	has_many :comment
	has_many :tag_gossip_links
	has_many :tags, through: :tag_gossip_links

	validates :title, length: { minimum: 3, maximum: 14},
	presence: true
	validates :content, 
	presence: true

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gossip
  belongs_to :user


end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :recipient_to_pm_links, foreign_key: 'received_message_id'
  has_many :recipients, foreign_key: 'recipient_id', class_name: "User", through: :recipient_to_pm_links
end

app/models/recipient_to_pm_link.rb
class RecipientToPmLink < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :received_message, class_name: "PrivateMessage"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_gossip_links
  has_many :gossips, through: :tag_gossip_links

  validates :title, uniqueness: true

end
 

app/models/tag_gossip_link.rb
class TagGossipLink < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag



end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :city
    has_many :gossip
    has_many :comment
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
	has_many :recipient_to_pm_links, foreign_key: 'recipient_id'
	has_many :received_messages, foreign_key: 'received_message_id', class_name: "PrivateMessage", through: :recipient_to_pm_links


	validates :first_name, length: { in: 2..40 }
	validates :last_name, length: { in: 2..40 }
    validates :email,
	    presence: true,
	    uniqueness: true,
	    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ActionController::Base

	def index

	end
	
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def team

  end

  def contact

  end

  def home
    @gossips = Gossip.all
  end

  def welcome
    @first_name = params['first_name']
  end

end

app/controllers/team_controller.rb
class TeamController < ApplicationController

	def index

	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contact/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contactez nous !</title>
</head>
<body>
<h1>Contactez-nous !</h1>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
     
    <title>TheTopTopGossipLioforest01</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%=team_index_path%>">Notre Team !</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%=contact_index_path%>">Nous contacter !</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown link
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
  </div>
</nav> <%= yield %>
  </body>
</html>

app/views/team/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
<h1>page team</h1>

</body>
</html>